# Generated by Django 3.0 on 2020-02-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Wantmatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='human',
            name='matched',
            field=models.ManyToManyField(to='match.Matched'),
        ),
        migrations.AddField(
            model_name='human',
            name='wantmatch',
            field=models.ManyToManyField(to='match.Wantmatch'),
        ),
    ]
