# Generated by Django 3.0 on 2020-03-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
