# Generated by Django 3.0 on 2020-03-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_auto_20200312_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_on']},
        ),
    ]
