# Generated by Django 3.0 on 2020-03-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20200312_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
